# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_auto_20170715_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marriage',
            name='album',
            field=models.ManyToManyField(null=True, to='family.Photograph'),
        ),
    ]
