# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0004_auto_20170716_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marriage',
            name='album',
            field=models.ManyToManyField(blank=True, to='family.Photograph'),
        ),
    ]
